/* This file was generated by syncqt. */
#ifndef QT_ACTIVEQT_VERSION_H
#define QT_ACTIVEQT_VERSION_H

#define ACTIVEQT_VERSION_STR "5.15.9"

#define ACTIVEQT_VERSION 0x050F09

#endif // QT_ACTIVEQT_VERSION_H
