/* This file was generated by syncqt. */
#ifndef QT_QT3DINPUT_VERSION_H
#define QT_QT3DINPUT_VERSION_H

#define QT3DINPUT_VERSION_STR "5.15.6"

#define QT3DINPUT_VERSION 0x050F06

#endif // QT_QT3DINPUT_VERSION_H
